//a Imports
use thiserror::Error;

//tp Error
/// Errors that can be generated by a [crate::Catalog]
#[derive(Debug, Error)]
pub enum Error {
    /// Failure to find an id within the catalog of stars
    #[error("Failed to find Id {0} in the catalog")]
    FailedToFindId(usize),
    /// Failure to find a star name in the name-to-id map of a catalog
    /// of stars
    #[error("Failed to find star name in the catalog")]
    FailedToFindName,
    /// Failed to read a CSV file for a catalog
    #[error("Failed to read CSV file")]
    #[from(csv::Error)]
    CsvError,
}
