//a Imports
use thiserror::Error;

//tp Error
/// Errors that can be generated by a [crate::Catalog]
#[derive(Debug, Error)]
pub enum Error {
    /// Std IO error
    #[error("{0}: {1}")]
    IO(String, #[source] std::io::Error),

    /// Json parsing error
    #[error("{0}")]
    Json(#[from] serde_json::Error),

    /// Unknown catalog
    #[error("Unknown builtin catalog")]
    UnknownCatalog,

    /// Unknown catalog extension
    #[error("Unknown builtin catalog extension")]
    UnknownCatalogExtension,

    /// Failure to find an id within the catalog of stars
    #[error("Failed to find Id {0} in the catalog")]
    FailedToFindId(usize),

    /// Failure to find a star name in the name-to-id map of a catalog
    /// of stars
    #[error("Failed to find star name in the catalog")]
    FailedToFindName,

    #[cfg(feature = "csv")]
    /// Failed to read a CSV file for a catalog
    #[error("Failed to read CSV file: {0}")]
    CsvError(#[from] csv::Error),

    #[cfg(feature = "postcard")]
    /// Failed to read a CSV file for a catalog
    #[error("Failed to read Postcard file: {0}")]
    Postcard(#[from] postcard::Error),
}

impl std::convert::From<(std::io::Error, String)> for Error {
    fn from((e, s): (std::io::Error, String)) -> Error {
        Error::IO(s, e)
    }
}
